version: '2'
networks:
  personal:
    # driver: bridge
    external:
      name: srv_personal

services:
  mongo:
    image: mongo:3.4 # latest (>3.6) removes deprecated $pushAll, breaking mongoose.
    volumes:
      - './data/db:/data/db'
    networks:
      - personal

  server:
    build: .
    links: 
      - mongo
    environment:
      - LETSENCRYPT_HOST=coding.karel-kroeze.nl
      - LETSENCRYPT_EMAIL=karel.kroeze@gmail.com
      - VIRTUAL_HOST=coding.karel-kroeze.nl
      - VIRTUAL_PORT=3000
    volumes:
      - ./data:/app/data
      - ./server/routes:/app/routes
      - ./frontend/dist:/app/public
    networks:
      - personal
