version: '2'
services:
  mongo:
    image: mongo
    volumes:
      - './data/db:/data/db'

  server:
    build: .
    links: 
      - mongo
    environment:
      - VIRTUAL_HOST=coding.karel-kroeze.nl
      - VIRTUAL_PORT=3000
    ports:
      - 3000:3000
    volumes:
      - ./data:/app/data
      - ./server/routes:/app/routes
      - ./frontend/dist:/app/public
